### ISSUE TITLE
关于前端的一些建议

### ISSUE THREAD

**Issue by ronggang** [tongyifan/Reseed-backend#11]
关注了好久，一直没用，今天用了一下，提些建议 😆

1、上传 `JSON` 文件后，希望有个状态显示，以免长时间等待时不知所措；或考虑使用 `websocket` ，服务端完成后通知浏览器；
2、建议站点选择时，双击或单击 `passkey` 框时可直接修改；
3、最后一步生成链接之后，我想在助手里适配这个页面，然后加一个 `发送到服务器` 按钮，这样就更方便了 😍

**Comment by tongyifan** [comment]
1 2 已更新

**Comment by ronggang** [comment]
第3点已适配，顺便写了个说明
https://github.com/ronggang/PT-Plugin-Plus/wiki/used-with-reseed
