### ISSUE TITLE
你好，请问下是否可以自定义站点支持呢？

### ISSUE THREAD

**Issue by piaoyun** [tongyifan/Reseed-backend#12]
是否会考虑开放接口，让用户自定义设置，支持的站点呢。看了线上的有些站点是不支持的呢

比如：pthome  谢谢！

**Comment by Rhilip** [comment]
不会开放的，目前也没有支持pthome站点的计划

**Comment by tongyifan** [comment]
这个工具的实质是获取站点种子库，将用户上传的文件结构与种子库比对，所以无法实现你所述的功能
