### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by tanpengsccd** [tongyifan/Reseed-backend#13]
![image](https://user-images.githubusercontent.com/13959880/67654309-0d913780-f988-11e9-95f5-5f0a1e8e2466.png)

昨天也试过了。一直这个错误

**Comment by Rhilip** [comment]
https://t.me/reseed_tongyifan_me/63

**Comment by tanpengsccd** [comment]
煲已经恢复了啊。都正常等来了

**Comment by Rhilip** [comment]
已修复

**Comment by tanpengsccd** [comment]
thx ,已经注册了
