### ISSUE TITLE
建议增加ipv6链接支持

### ISSUE THREAD

**Issue by Mokyyds** [tongyifan/Reseed-backend#14]
随着我国科技领域高速发展，ipv6逐渐已迈入千家万户。起初，我国只对高校开放的ipv6也逐渐走入个人家庭及企业。伴随着这样一个背景，我认为该项目作为全球知名项目，广大人民群众希望能开启这么一个功能。**开启后默认拼接所有支持ipv6链接下载的站点，默认给用户ipv6链接**
因为我这边关于南洋北洋的链接总是下载失败。。。

**Comment by tongyifan** [comment]
@Peachou 目前已知只有MT支持拼接&IPv6=1来下载IPv6专用链接，其他站点均无此功能，我并不能凭空为它们增加这一功能。

**Comment by Mokyyds** [comment]
好奇怪，我在校园网下竟然下南北洋链接出错。估计是我网络的问题，我以为都有ipv6的链接。
Thank you~
