### ISSUE TITLE
提供群晖的使用教程

### ISSUE THREAD

**Issue by tongyifan** [tongyifan/Reseed-backend#2]
然而手头没有群晖，虽然我感觉应该是ssh上去接下来和Linux一样，但是还是会有不会用的啊hhh

**Comment by reinasaster** [comment]
群晖我测试了reseed的包，生成json没有问题，没有前端账号，只测试了后端，谢谢大佬的辛苦工作

**Comment by tongyifan** [comment]
https://github.com/tongyifan/Reseed-backend/wiki/%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E7%BE%A4%E6%99%96synology%E7%94%A8%E6%88%B7%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
