### ISSUE TITLE
关于种子库

### ISSUE THREAD

**Issue by luyiming** [tongyifan/Reseed-backend#23]
请问种子库是爬取的吗？有没有可能自己部署这个服务吗？

**Comment by tongyifan** [comment]
种子库确实是爬取的，目前是使用rss做实时更新。我不认为有自己部署的必要，如果你想要增加站点或提其他需求请开issue或直接tg联系我

**Comment by luyiming** [comment]
原来如此，其实我就是比较好奇辅种是怎么实现的，结果看了一堆项目，IYUU啥的，要不就是直接读数据库，要不就是访问某个自建 api，我还以为 pt 站有开放查询接口什么的，原来是自己爬取的数据。Anyway，感谢你的回答～
