### ISSUE TITLE
使用reseed.py文件时报错

### ISSUE THREAD

**Issue by xby13030199338** [tongyifan/Reseed-backend#4]
File "reseed.py", line 11
SyntaxError: Non-ASCII character '\xe6' in file reseed.py on line 11, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
以上是报错信息 请教该如何解决？
系统架构是aarch64

**Comment by tongyifan** [comment]
请使用Python3，而不是Python2。
通过python -V或python3 -V查看版本

**Comment by xby13030199338** [comment]
明白 谢谢指教

**Comment by xby13030199338** [comment]
是不是没有北洋园的号就不能注册了。。。尴尬

**Comment by tongyifan** [comment]
暂时是这样的，见https://github.com/tongyifan/Reseed-backend/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by xby13030199338** [comment]
那么这个认证系统大概要什么时候做啊？

**Comment by tongyifan** [comment]
最快下个月可能会接入某个公网站点

**Comment by xby13030199338** [comment]
等不及了，已经注册了北洋园的帐号了，但是为什么在注册帐号的时候，填写了北洋园的密码之后显示密码无效。。确认密码是对的

**Comment by tongyifan** [comment]
是passkey而不是密码

**Comment by xby13030199338** [comment]
明白 感谢！
